sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: cyr010523

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSYFoxfFchwXUSxV8st
    access-key-secret: 3g4kdvcKkaCCokNJBxYZXCM3UFB9Wc
    bucket-name: cangqiong-hobo

  redis:
    host: localhost
    port: 6379
    password: cyr010523
    database: 10
    #database一共有16个数据库，0-15编号

  wechat:
    appid: wx3b937cd561c1edef
    secret: 3e476eafcdef807539bd3a1f3bd5846e

